version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bacphan1!
      POSTGRES_DB: sotalogistics_local
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    networks:
      - my_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: on-failure # Chỉ khởi động lại nếu container bị lỗi
    ports:
      - "9981:9981"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network


      

volumes:
  postgres-data:

networks:
    my_network:
      driver: bridge