version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: on-failure # Chỉ khởi động lại nếu container bị lỗi
    ports:
      - "8864:8864"
    env_file:
      - .env
